### ISSUE TITLE
Error on retrieving wallet status (testnet)

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Watcher#8]
I got this error using both Metamask and Nifty Wallet addresses.

Here the logs:

```
error on retrieving wallet status for  0x46336508b8705c3e20a40b1A26c1B5C8bABaDdea
Error: bad address checksum (argument="address", value="0x46336508b8705c3e20a40b1A26c1B5C8bABaDdea", code=INVALID_ARGUMENT, version=address/5.0.10) (argument="_owner", value="0x46336508b8705c3e20a40b1A26c1B5C8bABaDdea", code=INVALID_ARGUMENT, version=abi/5.0.7)
    at Logger.makeError (/home/ana/sovryn/watcher/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/home/ana/sovryn/watcher/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at Logger.throwArgumentError (/home/ana/sovryn/watcher/node_modules/@ethersproject/logger/lib/index.js:191:21)
    at AddressCoder.Coder._throwError (/home/ana/sovryn/watcher/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:40:16)
    at AddressCoder.encode (/home/ana/sovryn/watcher/node_modules/@ethersproject/abi/lib/coders/address.js:29:18)
    at /home/ana/sovryn/watcher/node_modules/@ethersproject/abi/lib/coders/array.js:71:19
    at Array.forEach (<anonymous>)
    at Object.pack (/home/ana/sovryn/watcher/node_modules/@ethersproject/abi/lib/coders/array.js:57:12)
    at TupleCoder.encode (/home/ana/sovryn/watcher/node_modules/@ethersproject/abi/lib/coders/tuple.js:36:24)
    at AbiCoder.encode (/home/ana/sovryn/watcher/node_modules/@ethersproject/abi/lib/abi-coder.js:86:15)
    at ABICoder.encodeParameters (/home/ana/sovryn/watcher/node_modules/web3-eth-abi/lib/index.js:121:27)
    at /home/ana/sovryn/watcher/node_modules/web3-eth-contract/lib/index.js:439:20
    at Array.map (<anonymous>)
    at Object._encodeMethodABI (/home/ana/sovryn/watcher/node_modules/web3-eth-contract/lib/index.js:438:8)
    at Object._processExecuteArguments (/home/ana/sovryn/watcher/node_modules/web3-eth-contract/lib/index.js:701:39)
    at Object._executeMethod (/home/ana/sovryn/watcher/node_modules/web3-eth-contract/lib/index.js:720:68) {
  reason: 'bad address checksum (argument="address", value="0x46336508b8705c3e20a40b1A26c1B5C8bABaDdea", code=INVALID_ARGUMENT, version=address/5.0.10)',
  code: 'INVALID_ARGUMENT',
  argument: '_owner',
  value: '0x46336508b8705c3e20a40b1A26c1B5C8bABaDdea'
}
(node:21214) UnhandledPromiseRejectionWarning: TypeError: (intermediate value) is not iterable
    at Liquidator.checkPositionsForLiquidations (/home/ana/sovryn/watcher/controller/liquidator.js:51:44)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7)
``` 

Debugging I see this happens when running the `getTokenInstance` function to get the BitPro contract. It seems the checksum for this contract address in testnet is failing (https://explorer.testnet.rsk.co/address/0x4da7997a819bb46b6758b9102234c289dd2ad3bf says a similar thing).

Very low priority

**Comment by jamiemadrox779** [comment]
.toLowerCase() should fix it
