### ISSUE TITLE
Error liquidating loan 0xdfac73e2cd26c1677d021530f33695de45cc02c87bd45cff2cc953ba35dc4895

### ISSUE THREAD

**Issue by Bitcoinera** [DistributedCollective/Sovryn-Watcher#9]
When running the liquidator with an account with both RBTC and DoC, I get the following error:

```
trying to liquidate loan 0xdfac73e2cd26c1677d021530f33695de45cc02c87bd45cff2cc953ba35dc4895 from wallet 0x46336508b8705c3e20a40b1a26c1b5c8babaddea, amount: 22212530809210473
Sending val: 22212530809210473
Nonce: 4
Error on liquidating loan 0xdfac73e2cd26c1677d021530f33695de45cc02c87bd45cff2cc953ba35dc4895
Error: Returned error: insufficient funds to pay for pending and new transaction
    at Object.ErrorResponse (/home/ana/sovryn/watcher/node_modules/web3-core-helpers/lib/errors.js:28:19)
    at /home/ana/sovryn/watcher/node_modules/web3-core-requestmanager/lib/index.js:303:36
    at XMLHttpRequest.request.onreadystatechange (/home/ana/sovryn/watcher/node_modules/web3-providers-http/lib/index.js:98:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/ana/sovryn/watcher/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/home/ana/sovryn/watcher/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/home/ana/sovryn/watcher/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/home/ana/sovryn/watcher/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:482:12)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  data: null
}
```

Appartently is trying to pay in BITPRO, a balance that I don't have any.

Debugging:

``` 
 CONTRACT TOKEN 0x4dA7997A819bb46B6758B9102234c289dD2Ad3bf
not enough balance on wallet. only use 0
``` 

I think the watcher shouldn't keep trying to liquidate loans if I don't have the required balance for that token. It is a quite unpredictable behavior. Either that or send the same amount worth in RBTC :thinking:

**Comment by Bitcoinera** [comment]
This was fixed by #20
